version: "3"

services:
  api:
    build:
      context: ./src
      args:
        ENVIRONMENT: DEVELOPMENT
    env_file: .env
    ports:
      - "${APP_PORT:-80}:8000"
    volumes:
      - ./src:/usr/src/app
    entrypoint: ./docker-entrypoint.sh
    command: "uvicorn MLabHubdjango.asgi:application --reload --host 0.0.0.0 --port ${APP_PORT:-8000}"
    restart: on-failure

  frontend:
    build:
      context: ./src
      target: webpack-builder
    volumes:
      - ./src/frontend:/usr/src/app
      - /usr/src/app/node_modules/
